<<<<<<< HEAD
quiet: False
dir: "{{.InterfaceDir}}/mocks"
mockname: "Mock{{.InterfaceName}}"
with-expecter: true
issue-845-fix: True
filename: "{{.InterfaceName | snakecase}}.go"

packages:
  github.com/wavesplatform/gowaves/pkg/networking:
    interfaces:
      Header:
      Protocol:
      Handler:
  github.com/wavesplatform/gowaves/pkg/blockchaininfo:
    interfaces:
      UpdatesPublisherInterface:
=======
dir: '{{.InterfaceDir}}'
structname: Mock{{.InterfaceName}}
template: testify
packages:
  github.com/wavesplatform/gowaves/pkg/networking:
    interfaces:
      Handler: {}
      Header: {}
      Protocol: {}
>>>>>>> master
