quiet: False
dir: "{{.InterfaceDir}}/mocks"
with-expecter: true
issue-845-fix: True
filename: "{{.InterfaceName | snakecase}}.go"

packages:
  github.com/wavesplatform/gowaves/pkg/networking:
    interfaces:
      Header:
      Protocol:
      Handler:
  github.com/wavesplatform/gowaves/pkg/blockchaininfo:
    interfaces:
      UpdatesExtensionState: