dir: '{{.InterfaceDir}}'
structname: Mock{{.InterfaceName}}
packages:
  github.com/wavesplatform/gowaves/pkg/networking:
    interfaces:
      Handler: {}
      Header: {}
      Protocol: {}
  github.com/wavesplatform/gowaves/pkg/blockchaininfo:
    interfaces:
      UpdatesPublisherInterface: {}
