// Code generated by "stringer -type event -trimprefix event"; DO NOT EDIT.

package network

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[eventPeerConnected-0]
	_ = x[eventPeerDisconnected-1]
	_ = x[eventScore-2]
	_ = x[eventGetPeers-3]
	_ = x[eventPeers-4]
	_ = x[eventFollowGroup-5]
	_ = x[eventFollowLeader-6]
	_ = x[eventBlacklistPeer-7]
	_ = x[eventBroadcastTransaction-8]
	_ = x[eventQuorumChanged-9]
	_ = x[eventFollowingModeChanged-10]
	_ = x[eventScoreUpdated-11]
	_ = x[eventAskPeers-12]
	_ = x[eventAnnounceScore-13]
	_ = x[eventBroadcastMicroBlockInv-14]
	_ = x[eventHalt-15]
}

const _event_name = "PeerConnectedPeerDisconnectedScoreGetPeersPeersFollowGroupFollowLeaderBlacklistPeerBroadcastTransactionQuorumChangedFollowingModeChangedScoreUpdatedAskPeersAnnounceScoreBroadcastMicroBlockInvHalt"

var _event_index = [...]uint8{0, 13, 29, 34, 42, 47, 58, 70, 83, 103, 116, 136, 148, 156, 169, 191, 195}

func (i event) String() string {
	if i < 0 || i >= event(len(_event_index)-1) {
		return "event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _event_name[_event_index[i]:_event_index[i+1]]
}
