// Code generated by "stringer -type event -trimprefix event"; DO NOT EDIT.

package node

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[eventTransaction-0]
	_ = x[eventBlock-1]
	_ = x[eventBlockIDs-2]
	_ = x[eventMicroBlockInv-3]
	_ = x[eventGetMicroBlock-4]
	_ = x[eventMicroBlock-5]
	_ = x[eventChangeSyncPeer-6]
	_ = x[eventResume-7]
	_ = x[eventSuspend-8]
	_ = x[eventBlockGenerated-9]
	_ = x[eventPersistenceRequired-10]
	_ = x[eventPersistenceComplete-11]
	_ = x[eventAbortSync-12]
	_ = x[eventBlockSequenceComplete-13]
	_ = x[eventBroadcastTransaction-14]
	_ = x[eventHalt-15]
}

const _event_name = "TransactionBlockBlockIDsMicroBlockInvGetMicroBlockMicroBlockChangeSyncPeerResumeSuspendBlockGeneratedPersistenceRequiredPersistenceCompleteAbortSyncBlockSequenceCompleteBroadcastTransactionHalt"

var _event_index = [...]uint8{0, 11, 16, 24, 37, 50, 60, 74, 80, 87, 101, 120, 139, 148, 169, 189, 193}

func (i event) String() string {
	if i < 0 || i >= event(len(_event_index)-1) {
		return "event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _event_name[_event_index[i]:_event_index[i+1]]
}
