// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockchain_api.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FeatureActivationStatus_BlockchainFeatureStatus int32

const (
	FeatureActivationStatus_UNDEFINED FeatureActivationStatus_BlockchainFeatureStatus = 0
	FeatureActivationStatus_APPROVED  FeatureActivationStatus_BlockchainFeatureStatus = 1
	FeatureActivationStatus_ACTIVATED FeatureActivationStatus_BlockchainFeatureStatus = 2
)

var FeatureActivationStatus_BlockchainFeatureStatus_name = map[int32]string{
	0: "UNDEFINED",
	1: "APPROVED",
	2: "ACTIVATED",
}

var FeatureActivationStatus_BlockchainFeatureStatus_value = map[string]int32{
	"UNDEFINED": 0,
	"APPROVED":  1,
	"ACTIVATED": 2,
}

func (x FeatureActivationStatus_BlockchainFeatureStatus) String() string {
	return proto.EnumName(FeatureActivationStatus_BlockchainFeatureStatus_name, int32(x))
}

func (FeatureActivationStatus_BlockchainFeatureStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5c7a93e2fcf598c, []int{2, 0}
}

type FeatureActivationStatus_NodeFeatureStatus int32

const (
	FeatureActivationStatus_NOT_IMPLEMENTED FeatureActivationStatus_NodeFeatureStatus = 0
	FeatureActivationStatus_IMPLEMENTED     FeatureActivationStatus_NodeFeatureStatus = 1
	FeatureActivationStatus_VOTED           FeatureActivationStatus_NodeFeatureStatus = 2
)

var FeatureActivationStatus_NodeFeatureStatus_name = map[int32]string{
	0: "NOT_IMPLEMENTED",
	1: "IMPLEMENTED",
	2: "VOTED",
}

var FeatureActivationStatus_NodeFeatureStatus_value = map[string]int32{
	"NOT_IMPLEMENTED": 0,
	"IMPLEMENTED":     1,
	"VOTED":           2,
}

func (x FeatureActivationStatus_NodeFeatureStatus) String() string {
	return proto.EnumName(FeatureActivationStatus_NodeFeatureStatus_name, int32(x))
}

func (FeatureActivationStatus_NodeFeatureStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c5c7a93e2fcf598c, []int{2, 1}
}

type ActivationStatusRequest struct {
	Height               int32    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivationStatusRequest) Reset()         { *m = ActivationStatusRequest{} }
func (m *ActivationStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ActivationStatusRequest) ProtoMessage()    {}
func (*ActivationStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c7a93e2fcf598c, []int{0}
}

func (m *ActivationStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivationStatusRequest.Unmarshal(m, b)
}
func (m *ActivationStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivationStatusRequest.Marshal(b, m, deterministic)
}
func (m *ActivationStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivationStatusRequest.Merge(m, src)
}
func (m *ActivationStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ActivationStatusRequest.Size(m)
}
func (m *ActivationStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivationStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivationStatusRequest proto.InternalMessageInfo

func (m *ActivationStatusRequest) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ActivationStatusResponse struct {
	Height               int32                      `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	VotingInterval       int32                      `protobuf:"varint,2,opt,name=voting_interval,json=votingInterval,proto3" json:"voting_interval,omitempty"`
	VotingThreshold      int32                      `protobuf:"varint,3,opt,name=voting_threshold,json=votingThreshold,proto3" json:"voting_threshold,omitempty"`
	NextCheck            int32                      `protobuf:"varint,4,opt,name=next_check,json=nextCheck,proto3" json:"next_check,omitempty"`
	Features             []*FeatureActivationStatus `protobuf:"bytes,5,rep,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ActivationStatusResponse) Reset()         { *m = ActivationStatusResponse{} }
func (m *ActivationStatusResponse) String() string { return proto.CompactTextString(m) }
func (*ActivationStatusResponse) ProtoMessage()    {}
func (*ActivationStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c7a93e2fcf598c, []int{1}
}

func (m *ActivationStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivationStatusResponse.Unmarshal(m, b)
}
func (m *ActivationStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivationStatusResponse.Marshal(b, m, deterministic)
}
func (m *ActivationStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivationStatusResponse.Merge(m, src)
}
func (m *ActivationStatusResponse) XXX_Size() int {
	return xxx_messageInfo_ActivationStatusResponse.Size(m)
}
func (m *ActivationStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivationStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivationStatusResponse proto.InternalMessageInfo

func (m *ActivationStatusResponse) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ActivationStatusResponse) GetVotingInterval() int32 {
	if m != nil {
		return m.VotingInterval
	}
	return 0
}

func (m *ActivationStatusResponse) GetVotingThreshold() int32 {
	if m != nil {
		return m.VotingThreshold
	}
	return 0
}

func (m *ActivationStatusResponse) GetNextCheck() int32 {
	if m != nil {
		return m.NextCheck
	}
	return 0
}

func (m *ActivationStatusResponse) GetFeatures() []*FeatureActivationStatus {
	if m != nil {
		return m.Features
	}
	return nil
}

type FeatureActivationStatus struct {
	Id                   int32                                           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string                                          `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	BlockchainStatus     FeatureActivationStatus_BlockchainFeatureStatus `protobuf:"varint,3,opt,name=blockchain_status,json=blockchainStatus,proto3,enum=waves.grpc.FeatureActivationStatus_BlockchainFeatureStatus" json:"blockchain_status,omitempty"`
	NodeStatus           FeatureActivationStatus_NodeFeatureStatus       `protobuf:"varint,4,opt,name=node_status,json=nodeStatus,proto3,enum=waves.grpc.FeatureActivationStatus_NodeFeatureStatus" json:"node_status,omitempty"`
	ActivationHeight     int32                                           `protobuf:"varint,5,opt,name=activation_height,json=activationHeight,proto3" json:"activation_height,omitempty"`
	SupportingBlocks     int32                                           `protobuf:"varint,6,opt,name=supporting_blocks,json=supportingBlocks,proto3" json:"supporting_blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                        `json:"-"`
	XXX_unrecognized     []byte                                          `json:"-"`
	XXX_sizecache        int32                                           `json:"-"`
}

func (m *FeatureActivationStatus) Reset()         { *m = FeatureActivationStatus{} }
func (m *FeatureActivationStatus) String() string { return proto.CompactTextString(m) }
func (*FeatureActivationStatus) ProtoMessage()    {}
func (*FeatureActivationStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c7a93e2fcf598c, []int{2}
}

func (m *FeatureActivationStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureActivationStatus.Unmarshal(m, b)
}
func (m *FeatureActivationStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureActivationStatus.Marshal(b, m, deterministic)
}
func (m *FeatureActivationStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureActivationStatus.Merge(m, src)
}
func (m *FeatureActivationStatus) XXX_Size() int {
	return xxx_messageInfo_FeatureActivationStatus.Size(m)
}
func (m *FeatureActivationStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureActivationStatus.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureActivationStatus proto.InternalMessageInfo

func (m *FeatureActivationStatus) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FeatureActivationStatus) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FeatureActivationStatus) GetBlockchainStatus() FeatureActivationStatus_BlockchainFeatureStatus {
	if m != nil {
		return m.BlockchainStatus
	}
	return FeatureActivationStatus_UNDEFINED
}

func (m *FeatureActivationStatus) GetNodeStatus() FeatureActivationStatus_NodeFeatureStatus {
	if m != nil {
		return m.NodeStatus
	}
	return FeatureActivationStatus_NOT_IMPLEMENTED
}

func (m *FeatureActivationStatus) GetActivationHeight() int32 {
	if m != nil {
		return m.ActivationHeight
	}
	return 0
}

func (m *FeatureActivationStatus) GetSupportingBlocks() int32 {
	if m != nil {
		return m.SupportingBlocks
	}
	return 0
}

type BaseTargetResponse struct {
	BaseTarget           int64    `protobuf:"varint,1,opt,name=base_target,json=baseTarget,proto3" json:"base_target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseTargetResponse) Reset()         { *m = BaseTargetResponse{} }
func (m *BaseTargetResponse) String() string { return proto.CompactTextString(m) }
func (*BaseTargetResponse) ProtoMessage()    {}
func (*BaseTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c7a93e2fcf598c, []int{3}
}

func (m *BaseTargetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseTargetResponse.Unmarshal(m, b)
}
func (m *BaseTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseTargetResponse.Marshal(b, m, deterministic)
}
func (m *BaseTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseTargetResponse.Merge(m, src)
}
func (m *BaseTargetResponse) XXX_Size() int {
	return xxx_messageInfo_BaseTargetResponse.Size(m)
}
func (m *BaseTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseTargetResponse proto.InternalMessageInfo

func (m *BaseTargetResponse) GetBaseTarget() int64 {
	if m != nil {
		return m.BaseTarget
	}
	return 0
}

type ScoreResponse struct {
	Score                []byte   `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScoreResponse) Reset()         { *m = ScoreResponse{} }
func (m *ScoreResponse) String() string { return proto.CompactTextString(m) }
func (*ScoreResponse) ProtoMessage()    {}
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5c7a93e2fcf598c, []int{4}
}

func (m *ScoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoreResponse.Unmarshal(m, b)
}
func (m *ScoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoreResponse.Marshal(b, m, deterministic)
}
func (m *ScoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoreResponse.Merge(m, src)
}
func (m *ScoreResponse) XXX_Size() int {
	return xxx_messageInfo_ScoreResponse.Size(m)
}
func (m *ScoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScoreResponse proto.InternalMessageInfo

func (m *ScoreResponse) GetScore() []byte {
	if m != nil {
		return m.Score
	}
	return nil
}

func init() {
	proto.RegisterEnum("waves.grpc.FeatureActivationStatus_BlockchainFeatureStatus", FeatureActivationStatus_BlockchainFeatureStatus_name, FeatureActivationStatus_BlockchainFeatureStatus_value)
	proto.RegisterEnum("waves.grpc.FeatureActivationStatus_NodeFeatureStatus", FeatureActivationStatus_NodeFeatureStatus_name, FeatureActivationStatus_NodeFeatureStatus_value)
	proto.RegisterType((*ActivationStatusRequest)(nil), "waves.grpc.ActivationStatusRequest")
	proto.RegisterType((*ActivationStatusResponse)(nil), "waves.grpc.ActivationStatusResponse")
	proto.RegisterType((*FeatureActivationStatus)(nil), "waves.grpc.FeatureActivationStatus")
	proto.RegisterType((*BaseTargetResponse)(nil), "waves.grpc.BaseTargetResponse")
	proto.RegisterType((*ScoreResponse)(nil), "waves.grpc.ScoreResponse")
}

func init() { proto.RegisterFile("blockchain_api.proto", fileDescriptor_c5c7a93e2fcf598c) }

var fileDescriptor_c5c7a93e2fcf598c = []byte{
	// 617 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xd1, 0x6e, 0xd3, 0x4a,
	0x10, 0xbd, 0x49, 0x9a, 0xaa, 0x99, 0x34, 0x6d, 0xb2, 0xad, 0x5a, 0xdf, 0x20, 0xa0, 0x0a, 0x20,
	0x8a, 0x2a, 0xb9, 0xa2, 0xa8, 0xbc, 0xf0, 0x80, 0xd2, 0xc6, 0x0d, 0x91, 0x68, 0x5a, 0xa5, 0x26,
	0x48, 0xbc, 0x98, 0x8d, 0x3d, 0xb5, 0x57, 0x75, 0xbc, 0xc6, 0xbb, 0x0e, 0xf0, 0xcc, 0xdf, 0xf0,
	0x61, 0x7c, 0x01, 0x1f, 0x80, 0xbc, 0x76, 0xed, 0x54, 0x21, 0xa8, 0x8f, 0x3e, 0x73, 0xe6, 0xcc,
	0x9c, 0x99, 0xf5, 0xc0, 0xf6, 0xc4, 0xe7, 0xf6, 0x8d, 0xed, 0x51, 0x16, 0x58, 0x34, 0x64, 0x7a,
	0x18, 0x71, 0xc9, 0x09, 0x7c, 0xa5, 0x33, 0x14, 0xba, 0x1b, 0x85, 0x76, 0xfb, 0x81, 0xcb, 0xb9,
	0xeb, 0xe3, 0xa1, 0x8a, 0x4c, 0xe2, 0xeb, 0x43, 0x9c, 0x86, 0xf2, 0x7b, 0x4a, 0xec, 0xbc, 0x84,
	0xdd, 0xae, 0x2d, 0xd9, 0x8c, 0x4a, 0xc6, 0x83, 0x2b, 0x49, 0x65, 0x2c, 0x46, 0xf8, 0x25, 0x46,
	0x21, 0xc9, 0x0e, 0xac, 0x7a, 0xc8, 0x5c, 0x4f, 0x6a, 0xa5, 0xbd, 0xd2, 0x7e, 0x75, 0x94, 0x7d,
	0x75, 0x7e, 0x95, 0x40, 0x5b, 0xcc, 0x11, 0x21, 0x0f, 0x04, 0x2e, 0x4b, 0x22, 0xcf, 0x61, 0x73,
	0xc6, 0x25, 0x0b, 0x5c, 0x8b, 0x05, 0x12, 0xa3, 0x19, 0xf5, 0xb5, 0xb2, 0x22, 0x6c, 0xa4, 0xf0,
	0x20, 0x43, 0xc9, 0x0b, 0x68, 0x66, 0x44, 0xe9, 0x45, 0x28, 0x3c, 0xee, 0x3b, 0x5a, 0x45, 0x31,
	0x33, 0x01, 0xf3, 0x16, 0x26, 0x0f, 0x01, 0x02, 0xfc, 0x26, 0x2d, 0xdb, 0x43, 0xfb, 0x46, 0x5b,
	0x51, 0xa4, 0x5a, 0x82, 0x9c, 0x26, 0x00, 0x79, 0x0b, 0x6b, 0xd7, 0x48, 0x65, 0x1c, 0xa1, 0xd0,
	0xaa, 0x7b, 0x95, 0xfd, 0xfa, 0xd1, 0x13, 0xbd, 0x18, 0x8b, 0x7e, 0x96, 0xc6, 0x16, 0x9c, 0xe4,
	0x49, 0x9d, 0xdf, 0x15, 0xd8, 0x5d, 0xc2, 0x22, 0x1b, 0x50, 0x66, 0x4e, 0xe6, 0xb1, 0xcc, 0x1c,
	0xb2, 0x07, 0x75, 0x07, 0x85, 0x1d, 0xb1, 0x30, 0x21, 0x29, 0x6f, 0xb5, 0xd1, 0x3c, 0x44, 0x3c,
	0x68, 0xcd, 0xad, 0x4a, 0x28, 0x19, 0xe5, 0x6c, 0xe3, 0xe8, 0xcd, 0x3d, 0xfa, 0xd2, 0x4f, 0xf2,
	0xe4, 0x8c, 0x91, 0xf5, 0xdb, 0x2c, 0x54, 0xb3, 0xde, 0xc6, 0x50, 0x0f, 0xb8, 0x83, 0xb7, 0x35,
	0x56, 0x54, 0x8d, 0xe3, 0xfb, 0xd4, 0x18, 0x72, 0x07, 0xef, 0xaa, 0x43, 0xa2, 0x94, 0xe9, 0x1e,
	0x40, 0x8b, 0xe6, 0x19, 0x56, 0xb6, 0xe6, 0xaa, 0x1a, 0x41, 0xb3, 0x08, 0xbc, 0x4b, 0x17, 0x7e,
	0x00, 0x2d, 0x11, 0x87, 0x21, 0x8f, 0xd4, 0x2e, 0x55, 0x8f, 0x42, 0x5b, 0x4d, 0xc9, 0x45, 0x40,
	0x99, 0x12, 0x1d, 0x03, 0x76, 0x97, 0xd8, 0x23, 0x0d, 0xa8, 0x7d, 0x18, 0xf6, 0x8c, 0xb3, 0xc1,
	0xd0, 0xe8, 0x35, 0xff, 0x23, 0xeb, 0xb0, 0xd6, 0xbd, 0xbc, 0x1c, 0x5d, 0x8c, 0x8d, 0x5e, 0xb3,
	0x94, 0x04, 0xbb, 0xa7, 0xe6, 0x60, 0xdc, 0x35, 0x8d, 0x5e, 0xb3, 0xdc, 0xe9, 0x41, 0x6b, 0xc1,
	0x01, 0xd9, 0x82, 0xcd, 0xe1, 0x85, 0x69, 0x0d, 0xce, 0x2f, 0xdf, 0x1b, 0xe7, 0xc6, 0xd0, 0x54,
	0x32, 0x9b, 0x50, 0x9f, 0x07, 0x4a, 0xa4, 0x06, 0xd5, 0xf1, 0x45, 0xaa, 0x72, 0x0c, 0xe4, 0x84,
	0x0a, 0x34, 0x69, 0xe4, 0xa2, 0xcc, 0x1f, 0xf6, 0x63, 0xa8, 0x4f, 0xa8, 0x40, 0x4b, 0x2a, 0x58,
	0x6d, 0xbe, 0x32, 0x82, 0x49, 0x4e, 0xec, 0x3c, 0x83, 0xc6, 0x95, 0xcd, 0x23, 0xcc, 0x33, 0xb6,
	0xa1, 0x2a, 0x12, 0x40, 0x71, 0xd7, 0x47, 0xe9, 0xc7, 0xd1, 0x8f, 0x32, 0x34, 0x0a, 0xaf, 0xdd,
	0x90, 0x91, 0xcf, 0xb0, 0xd5, 0x47, 0xb9, 0xf0, 0xc2, 0xee, 0x3c, 0xd6, 0x25, 0xff, 0x68, 0xfb,
	0xe9, 0xbf, 0x49, 0x59, 0x27, 0x7d, 0x68, 0xf4, 0x51, 0x16, 0xa6, 0xc8, 0x8e, 0x9e, 0xde, 0x04,
	0xfd, 0xf6, 0x26, 0xe8, 0x46, 0x72, 0x13, 0xda, 0x8f, 0xe6, 0xe5, 0xfe, 0x32, 0x84, 0x3e, 0x90,
	0x3e, 0xca, 0xd3, 0x78, 0x1a, 0xfb, 0x54, 0xb2, 0x19, 0x2a, 0xc3, 0x4b, 0xd5, 0xfe, 0x9f, 0x57,
	0xbb, 0x33, 0x9b, 0x93, 0xd7, 0xd0, 0xb6, 0xf9, 0x34, 0x8d, 0x87, 0x3e, 0x95, 0xd7, 0x3c, 0x9a,
	0xea, 0xc9, 0xf9, 0x4a, 0xb8, 0x9f, 0xea, 0xb6, 0xcf, 0x30, 0x90, 0x87, 0xc9, 0xc7, 0xcf, 0x32,
	0x7c, 0x54, 0x2a, 0xfd, 0x28, 0xb4, 0x27, 0xab, 0xaa, 0xc4, 0xab, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x84, 0xea, 0xcc, 0x8d, 0xf6, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BlockchainApiClient is the client API for BlockchainApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BlockchainApiClient interface {
	GetActivationStatus(ctx context.Context, in *ActivationStatusRequest, opts ...grpc.CallOption) (*ActivationStatusResponse, error)
	GetBaseTarget(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BaseTargetResponse, error)
	GetCumulativeScore(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ScoreResponse, error)
}

type blockchainApiClient struct {
	cc *grpc.ClientConn
}

func NewBlockchainApiClient(cc *grpc.ClientConn) BlockchainApiClient {
	return &blockchainApiClient{cc}
}

func (c *blockchainApiClient) GetActivationStatus(ctx context.Context, in *ActivationStatusRequest, opts ...grpc.CallOption) (*ActivationStatusResponse, error) {
	out := new(ActivationStatusResponse)
	err := c.cc.Invoke(ctx, "/waves.grpc.BlockchainApi/GetActivationStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainApiClient) GetBaseTarget(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*BaseTargetResponse, error) {
	out := new(BaseTargetResponse)
	err := c.cc.Invoke(ctx, "/waves.grpc.BlockchainApi/GetBaseTarget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockchainApiClient) GetCumulativeScore(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ScoreResponse, error) {
	out := new(ScoreResponse)
	err := c.cc.Invoke(ctx, "/waves.grpc.BlockchainApi/GetCumulativeScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockchainApiServer is the server API for BlockchainApi service.
type BlockchainApiServer interface {
	GetActivationStatus(context.Context, *ActivationStatusRequest) (*ActivationStatusResponse, error)
	GetBaseTarget(context.Context, *empty.Empty) (*BaseTargetResponse, error)
	GetCumulativeScore(context.Context, *empty.Empty) (*ScoreResponse, error)
}

// UnimplementedBlockchainApiServer can be embedded to have forward compatible implementations.
type UnimplementedBlockchainApiServer struct {
}

func (*UnimplementedBlockchainApiServer) GetActivationStatus(ctx context.Context, req *ActivationStatusRequest) (*ActivationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivationStatus not implemented")
}
func (*UnimplementedBlockchainApiServer) GetBaseTarget(ctx context.Context, req *empty.Empty) (*BaseTargetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaseTarget not implemented")
}
func (*UnimplementedBlockchainApiServer) GetCumulativeScore(ctx context.Context, req *empty.Empty) (*ScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCumulativeScore not implemented")
}

func RegisterBlockchainApiServer(s *grpc.Server, srv BlockchainApiServer) {
	s.RegisterService(&_BlockchainApi_serviceDesc, srv)
}

func _BlockchainApi_GetActivationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainApiServer).GetActivationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/waves.grpc.BlockchainApi/GetActivationStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainApiServer).GetActivationStatus(ctx, req.(*ActivationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainApi_GetBaseTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainApiServer).GetBaseTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/waves.grpc.BlockchainApi/GetBaseTarget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainApiServer).GetBaseTarget(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockchainApi_GetCumulativeScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockchainApiServer).GetCumulativeScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/waves.grpc.BlockchainApi/GetCumulativeScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockchainApiServer).GetCumulativeScore(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockchainApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "waves.grpc.BlockchainApi",
	HandlerType: (*BlockchainApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActivationStatus",
			Handler:    _BlockchainApi_GetActivationStatus_Handler,
		},
		{
			MethodName: "GetBaseTarget",
			Handler:    _BlockchainApi_GetBaseTarget_Handler,
		},
		{
			MethodName: "GetCumulativeScore",
			Handler:    _BlockchainApi_GetCumulativeScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockchain_api.proto",
}
