// Code generated by protoc-gen-go. DO NOT EDIT.
// source: script.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Script struct {
	Bytes                []byte   `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Script) Reset()         { *m = Script{} }
func (m *Script) String() string { return proto.CompactTextString(m) }
func (*Script) ProtoMessage()    {}
func (*Script) Descriptor() ([]byte, []int) {
	return fileDescriptor_01e8311d1fb507af, []int{0}
}

func (m *Script) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Script.Unmarshal(m, b)
}
func (m *Script) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Script.Marshal(b, m, deterministic)
}
func (m *Script) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Script.Merge(m, src)
}
func (m *Script) XXX_Size() int {
	return xxx_messageInfo_Script.Size(m)
}
func (m *Script) XXX_DiscardUnknown() {
	xxx_messageInfo_Script.DiscardUnknown(m)
}

var xxx_messageInfo_Script proto.InternalMessageInfo

func (m *Script) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func init() {
	proto.RegisterType((*Script)(nil), "Script")
}

func init() { proto.RegisterFile("script.proto", fileDescriptor_01e8311d1fb507af) }

var fileDescriptor_01e8311d1fb507af = []byte{
	// 119 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x2e, 0xca,
	0x2c, 0x28, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe3, 0x62, 0x0b, 0x06, 0xf3, 0x85,
	0x44, 0xb8, 0x58, 0x93, 0x2a, 0x4b, 0x52, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x20,
	0x1c, 0x27, 0x53, 0x2e, 0xb5, 0xe4, 0xfc, 0x5c, 0xbd, 0xf2, 0xc4, 0xb2, 0xd4, 0xe2, 0x82, 0x9c,
	0xc4, 0x92, 0xb4, 0xfc, 0xa2, 0x5c, 0x88, 0xd6, 0xa4, 0xd2, 0x34, 0xbd, 0x92, 0xa2, 0xc4, 0xbc,
	0xe2, 0xc4, 0xe4, 0x92, 0xcc, 0xfc, 0xbc, 0x28, 0xee, 0xe4, 0x9c, 0xcc, 0xd4, 0xbc, 0x12, 0xfd,
	0xf4, 0xa2, 0x82, 0xe4, 0x24, 0x36, 0xb0, 0x12, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9,
	0x36, 0xa0, 0x5f, 0x6d, 0x00, 0x00, 0x00,
}
