#!/bin/sh
set -e
# Automatically added by dh_installinit/12.10ubuntu1
if [ -x "/etc/init.d/PACKAGE" ] && [ "$1" = remove ]; then
	invoke-rc.d PACKAGE stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/12.10ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'PACKAGE.service' >/dev/null || true
fi
# End automatically added section
