// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ride

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/wavesplatform/gowaves/pkg/proto"
	"github.com/wavesplatform/gowaves/pkg/ride/ast"
	"github.com/wavesplatform/gowaves/pkg/types"
)

// NewMockEnvironment creates a new instance of MockEnvironment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnvironment(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnvironment {
	mock := &MockEnvironment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEnvironment is an autogenerated mock type for the environment type
type MockEnvironment struct {
	mock.Mock
}

type MockEnvironment_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnvironment) EXPECT() *MockEnvironment_Expecter {
	return &MockEnvironment_Expecter{mock: &_m.Mock}
}

// block provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) block() rideType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for block")
	}

	var r0 rideType
	if returnFunc, ok := ret.Get(0).(func() rideType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rideType)
		}
	}
	return r0
}

// MockEnvironment_block_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'block'
type MockEnvironment_block_Call struct {
	*mock.Call
}

// block is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) block() *MockEnvironment_block_Call {
	return &MockEnvironment_block_Call{Call: _e.mock.On("block")}
}

func (_c *MockEnvironment_block_Call) Run(run func()) *MockEnvironment_block_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_block_Call) Return(rideTypeMoqParam rideType) *MockEnvironment_block_Call {
	_c.Call.Return(rideTypeMoqParam)
	return _c
}

func (_c *MockEnvironment_block_Call) RunAndReturn(run func() rideType) *MockEnvironment_block_Call {
	_c.Call.Return(run)
	return _c
}

// blockRewardDistributionActivated provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) blockRewardDistributionActivated() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for blockRewardDistributionActivated")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEnvironment_blockRewardDistributionActivated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'blockRewardDistributionActivated'
type MockEnvironment_blockRewardDistributionActivated_Call struct {
	*mock.Call
}

// blockRewardDistributionActivated is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) blockRewardDistributionActivated() *MockEnvironment_blockRewardDistributionActivated_Call {
	return &MockEnvironment_blockRewardDistributionActivated_Call{Call: _e.mock.On("blockRewardDistributionActivated")}
}

func (_c *MockEnvironment_blockRewardDistributionActivated_Call) Run(run func()) *MockEnvironment_blockRewardDistributionActivated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_blockRewardDistributionActivated_Call) Return(b bool) *MockEnvironment_blockRewardDistributionActivated_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEnvironment_blockRewardDistributionActivated_Call) RunAndReturn(run func() bool) *MockEnvironment_blockRewardDistributionActivated_Call {
	_c.Call.Return(run)
	return _c
}

// blockV5Activated provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) blockV5Activated() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for blockV5Activated")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEnvironment_blockV5Activated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'blockV5Activated'
type MockEnvironment_blockV5Activated_Call struct {
	*mock.Call
}

// blockV5Activated is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) blockV5Activated() *MockEnvironment_blockV5Activated_Call {
	return &MockEnvironment_blockV5Activated_Call{Call: _e.mock.On("blockV5Activated")}
}

func (_c *MockEnvironment_blockV5Activated_Call) Run(run func()) *MockEnvironment_blockV5Activated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_blockV5Activated_Call) Return(b bool) *MockEnvironment_blockV5Activated_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEnvironment_blockV5Activated_Call) RunAndReturn(run func() bool) *MockEnvironment_blockV5Activated_Call {
	_c.Call.Return(run)
	return _c
}

// checkMessageLength provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) checkMessageLength(n int) bool {
	ret := _mock.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for checkMessageLength")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int) bool); ok {
		r0 = returnFunc(n)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEnvironment_checkMessageLength_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'checkMessageLength'
type MockEnvironment_checkMessageLength_Call struct {
	*mock.Call
}

// checkMessageLength is a helper method to define mock.On call
//   - n int
func (_e *MockEnvironment_Expecter) checkMessageLength(n interface{}) *MockEnvironment_checkMessageLength_Call {
	return &MockEnvironment_checkMessageLength_Call{Call: _e.mock.On("checkMessageLength", n)}
}

func (_c *MockEnvironment_checkMessageLength_Call) Run(run func(n int)) *MockEnvironment_checkMessageLength_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEnvironment_checkMessageLength_Call) Return(b bool) *MockEnvironment_checkMessageLength_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEnvironment_checkMessageLength_Call) RunAndReturn(run func(n int) bool) *MockEnvironment_checkMessageLength_Call {
	_c.Call.Return(run)
	return _c
}

// complexityCalculator provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) complexityCalculator() complexityCalculator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for complexityCalculator")
	}

	var r0 complexityCalculator
	if returnFunc, ok := ret.Get(0).(func() complexityCalculator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(complexityCalculator)
		}
	}
	return r0
}

// MockEnvironment_complexityCalculator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'complexityCalculator'
type MockEnvironment_complexityCalculator_Call struct {
	*mock.Call
}

// complexityCalculator is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) complexityCalculator() *MockEnvironment_complexityCalculator_Call {
	return &MockEnvironment_complexityCalculator_Call{Call: _e.mock.On("complexityCalculator")}
}

func (_c *MockEnvironment_complexityCalculator_Call) Run(run func()) *MockEnvironment_complexityCalculator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_complexityCalculator_Call) Return(complexityCalculatorMoqParam complexityCalculator) *MockEnvironment_complexityCalculator_Call {
	_c.Call.Return(complexityCalculatorMoqParam)
	return _c
}

func (_c *MockEnvironment_complexityCalculator_Call) RunAndReturn(run func() complexityCalculator) *MockEnvironment_complexityCalculator_Call {
	_c.Call.Return(run)
	return _c
}

// consensusImprovementsActivated provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) consensusImprovementsActivated() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for consensusImprovementsActivated")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEnvironment_consensusImprovementsActivated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'consensusImprovementsActivated'
type MockEnvironment_consensusImprovementsActivated_Call struct {
	*mock.Call
}

// consensusImprovementsActivated is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) consensusImprovementsActivated() *MockEnvironment_consensusImprovementsActivated_Call {
	return &MockEnvironment_consensusImprovementsActivated_Call{Call: _e.mock.On("consensusImprovementsActivated")}
}

func (_c *MockEnvironment_consensusImprovementsActivated_Call) Run(run func()) *MockEnvironment_consensusImprovementsActivated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_consensusImprovementsActivated_Call) Return(b bool) *MockEnvironment_consensusImprovementsActivated_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEnvironment_consensusImprovementsActivated_Call) RunAndReturn(run func() bool) *MockEnvironment_consensusImprovementsActivated_Call {
	_c.Call.Return(run)
	return _c
}

// height provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) height() rideInt {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for height")
	}

	var r0 rideInt
	if returnFunc, ok := ret.Get(0).(func() rideInt); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(rideInt)
	}
	return r0
}

// MockEnvironment_height_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'height'
type MockEnvironment_height_Call struct {
	*mock.Call
}

// height is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) height() *MockEnvironment_height_Call {
	return &MockEnvironment_height_Call{Call: _e.mock.On("height")}
}

func (_c *MockEnvironment_height_Call) Run(run func()) *MockEnvironment_height_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_height_Call) Return(rideIntMoqParam rideInt) *MockEnvironment_height_Call {
	_c.Call.Return(rideIntMoqParam)
	return _c
}

func (_c *MockEnvironment_height_Call) RunAndReturn(run func() rideInt) *MockEnvironment_height_Call {
	_c.Call.Return(run)
	return _c
}

// internalPaymentsValidationHeight provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) internalPaymentsValidationHeight() proto.Height {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for internalPaymentsValidationHeight")
	}

	var r0 proto.Height
	if returnFunc, ok := ret.Get(0).(func() proto.Height); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(proto.Height)
	}
	return r0
}

// MockEnvironment_internalPaymentsValidationHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'internalPaymentsValidationHeight'
type MockEnvironment_internalPaymentsValidationHeight_Call struct {
	*mock.Call
}

// internalPaymentsValidationHeight is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) internalPaymentsValidationHeight() *MockEnvironment_internalPaymentsValidationHeight_Call {
	return &MockEnvironment_internalPaymentsValidationHeight_Call{Call: _e.mock.On("internalPaymentsValidationHeight")}
}

func (_c *MockEnvironment_internalPaymentsValidationHeight_Call) Run(run func()) *MockEnvironment_internalPaymentsValidationHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_internalPaymentsValidationHeight_Call) Return(v proto.Height) *MockEnvironment_internalPaymentsValidationHeight_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockEnvironment_internalPaymentsValidationHeight_Call) RunAndReturn(run func() proto.Height) *MockEnvironment_internalPaymentsValidationHeight_Call {
	_c.Call.Return(run)
	return _c
}

// invocation provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) invocation() rideType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for invocation")
	}

	var r0 rideType
	if returnFunc, ok := ret.Get(0).(func() rideType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rideType)
		}
	}
	return r0
}

// MockEnvironment_invocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'invocation'
type MockEnvironment_invocation_Call struct {
	*mock.Call
}

// invocation is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) invocation() *MockEnvironment_invocation_Call {
	return &MockEnvironment_invocation_Call{Call: _e.mock.On("invocation")}
}

func (_c *MockEnvironment_invocation_Call) Run(run func()) *MockEnvironment_invocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_invocation_Call) Return(rideTypeMoqParam rideType) *MockEnvironment_invocation_Call {
	_c.Call.Return(rideTypeMoqParam)
	return _c
}

func (_c *MockEnvironment_invocation_Call) RunAndReturn(run func() rideType) *MockEnvironment_invocation_Call {
	_c.Call.Return(run)
	return _c
}

// isProtobufTx provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) isProtobufTx() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for isProtobufTx")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEnvironment_isProtobufTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isProtobufTx'
type MockEnvironment_isProtobufTx_Call struct {
	*mock.Call
}

// isProtobufTx is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) isProtobufTx() *MockEnvironment_isProtobufTx_Call {
	return &MockEnvironment_isProtobufTx_Call{Call: _e.mock.On("isProtobufTx")}
}

func (_c *MockEnvironment_isProtobufTx_Call) Run(run func()) *MockEnvironment_isProtobufTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_isProtobufTx_Call) Return(b bool) *MockEnvironment_isProtobufTx_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEnvironment_isProtobufTx_Call) RunAndReturn(run func() bool) *MockEnvironment_isProtobufTx_Call {
	_c.Call.Return(run)
	return _c
}

// libVersion provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) libVersion() (ast.LibraryVersion, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for libVersion")
	}

	var r0 ast.LibraryVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (ast.LibraryVersion, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() ast.LibraryVersion); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ast.LibraryVersion)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEnvironment_libVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'libVersion'
type MockEnvironment_libVersion_Call struct {
	*mock.Call
}

// libVersion is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) libVersion() *MockEnvironment_libVersion_Call {
	return &MockEnvironment_libVersion_Call{Call: _e.mock.On("libVersion")}
}

func (_c *MockEnvironment_libVersion_Call) Run(run func()) *MockEnvironment_libVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_libVersion_Call) Return(libraryVersion ast.LibraryVersion, err error) *MockEnvironment_libVersion_Call {
	_c.Call.Return(libraryVersion, err)
	return _c
}

func (_c *MockEnvironment_libVersion_Call) RunAndReturn(run func() (ast.LibraryVersion, error)) *MockEnvironment_libVersion_Call {
	_c.Call.Return(run)
	return _c
}

// lightNodeActivated provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) lightNodeActivated() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for lightNodeActivated")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEnvironment_lightNodeActivated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'lightNodeActivated'
type MockEnvironment_lightNodeActivated_Call struct {
	*mock.Call
}

// lightNodeActivated is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) lightNodeActivated() *MockEnvironment_lightNodeActivated_Call {
	return &MockEnvironment_lightNodeActivated_Call{Call: _e.mock.On("lightNodeActivated")}
}

func (_c *MockEnvironment_lightNodeActivated_Call) Run(run func()) *MockEnvironment_lightNodeActivated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_lightNodeActivated_Call) Return(b bool) *MockEnvironment_lightNodeActivated_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEnvironment_lightNodeActivated_Call) RunAndReturn(run func() bool) *MockEnvironment_lightNodeActivated_Call {
	_c.Call.Return(run)
	return _c
}

// maxDataEntriesSize provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) maxDataEntriesSize() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for maxDataEntriesSize")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockEnvironment_maxDataEntriesSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'maxDataEntriesSize'
type MockEnvironment_maxDataEntriesSize_Call struct {
	*mock.Call
}

// maxDataEntriesSize is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) maxDataEntriesSize() *MockEnvironment_maxDataEntriesSize_Call {
	return &MockEnvironment_maxDataEntriesSize_Call{Call: _e.mock.On("maxDataEntriesSize")}
}

func (_c *MockEnvironment_maxDataEntriesSize_Call) Run(run func()) *MockEnvironment_maxDataEntriesSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_maxDataEntriesSize_Call) Return(n int) *MockEnvironment_maxDataEntriesSize_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockEnvironment_maxDataEntriesSize_Call) RunAndReturn(run func() int) *MockEnvironment_maxDataEntriesSize_Call {
	_c.Call.Return(run)
	return _c
}

// paymentsFixActivated provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) paymentsFixActivated() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for paymentsFixActivated")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEnvironment_paymentsFixActivated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'paymentsFixActivated'
type MockEnvironment_paymentsFixActivated_Call struct {
	*mock.Call
}

// paymentsFixActivated is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) paymentsFixActivated() *MockEnvironment_paymentsFixActivated_Call {
	return &MockEnvironment_paymentsFixActivated_Call{Call: _e.mock.On("paymentsFixActivated")}
}

func (_c *MockEnvironment_paymentsFixActivated_Call) Run(run func()) *MockEnvironment_paymentsFixActivated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_paymentsFixActivated_Call) Return(b bool) *MockEnvironment_paymentsFixActivated_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEnvironment_paymentsFixActivated_Call) RunAndReturn(run func() bool) *MockEnvironment_paymentsFixActivated_Call {
	_c.Call.Return(run)
	return _c
}

// paymentsFixAfterHeight provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) paymentsFixAfterHeight() proto.Height {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for paymentsFixAfterHeight")
	}

	var r0 proto.Height
	if returnFunc, ok := ret.Get(0).(func() proto.Height); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(proto.Height)
	}
	return r0
}

// MockEnvironment_paymentsFixAfterHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'paymentsFixAfterHeight'
type MockEnvironment_paymentsFixAfterHeight_Call struct {
	*mock.Call
}

// paymentsFixAfterHeight is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) paymentsFixAfterHeight() *MockEnvironment_paymentsFixAfterHeight_Call {
	return &MockEnvironment_paymentsFixAfterHeight_Call{Call: _e.mock.On("paymentsFixAfterHeight")}
}

func (_c *MockEnvironment_paymentsFixAfterHeight_Call) Run(run func()) *MockEnvironment_paymentsFixAfterHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_paymentsFixAfterHeight_Call) Return(v proto.Height) *MockEnvironment_paymentsFixAfterHeight_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockEnvironment_paymentsFixAfterHeight_Call) RunAndReturn(run func() proto.Height) *MockEnvironment_paymentsFixAfterHeight_Call {
	_c.Call.Return(run)
	return _c
}

// rideV6Activated provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) rideV6Activated() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for rideV6Activated")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEnvironment_rideV6Activated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'rideV6Activated'
type MockEnvironment_rideV6Activated_Call struct {
	*mock.Call
}

// rideV6Activated is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) rideV6Activated() *MockEnvironment_rideV6Activated_Call {
	return &MockEnvironment_rideV6Activated_Call{Call: _e.mock.On("rideV6Activated")}
}

func (_c *MockEnvironment_rideV6Activated_Call) Run(run func()) *MockEnvironment_rideV6Activated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_rideV6Activated_Call) Return(b bool) *MockEnvironment_rideV6Activated_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEnvironment_rideV6Activated_Call) RunAndReturn(run func() bool) *MockEnvironment_rideV6Activated_Call {
	_c.Call.Return(run)
	return _c
}

// scheme provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) scheme() byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for scheme")
	}

	var r0 byte
	if returnFunc, ok := ret.Get(0).(func() byte); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(byte)
	}
	return r0
}

// MockEnvironment_scheme_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'scheme'
type MockEnvironment_scheme_Call struct {
	*mock.Call
}

// scheme is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) scheme() *MockEnvironment_scheme_Call {
	return &MockEnvironment_scheme_Call{Call: _e.mock.On("scheme")}
}

func (_c *MockEnvironment_scheme_Call) Run(run func()) *MockEnvironment_scheme_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_scheme_Call) Return(v byte) *MockEnvironment_scheme_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockEnvironment_scheme_Call) RunAndReturn(run func() byte) *MockEnvironment_scheme_Call {
	_c.Call.Return(run)
	return _c
}

// setComplexityCalculator provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) setComplexityCalculator(cc complexityCalculator) {
	_mock.Called(cc)
	return
}

// MockEnvironment_setComplexityCalculator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setComplexityCalculator'
type MockEnvironment_setComplexityCalculator_Call struct {
	*mock.Call
}

// setComplexityCalculator is a helper method to define mock.On call
//   - cc complexityCalculator
func (_e *MockEnvironment_Expecter) setComplexityCalculator(cc interface{}) *MockEnvironment_setComplexityCalculator_Call {
	return &MockEnvironment_setComplexityCalculator_Call{Call: _e.mock.On("setComplexityCalculator", cc)}
}

func (_c *MockEnvironment_setComplexityCalculator_Call) Run(run func(cc complexityCalculator)) *MockEnvironment_setComplexityCalculator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 complexityCalculator
		if args[0] != nil {
			arg0 = args[0].(complexityCalculator)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEnvironment_setComplexityCalculator_Call) Return() *MockEnvironment_setComplexityCalculator_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnvironment_setComplexityCalculator_Call) RunAndReturn(run func(cc complexityCalculator)) *MockEnvironment_setComplexityCalculator_Call {
	_c.Run(run)
	return _c
}

// setInvocation provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) setInvocation(inv rideType) {
	_mock.Called(inv)
	return
}

// MockEnvironment_setInvocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setInvocation'
type MockEnvironment_setInvocation_Call struct {
	*mock.Call
}

// setInvocation is a helper method to define mock.On call
//   - inv rideType
func (_e *MockEnvironment_Expecter) setInvocation(inv interface{}) *MockEnvironment_setInvocation_Call {
	return &MockEnvironment_setInvocation_Call{Call: _e.mock.On("setInvocation", inv)}
}

func (_c *MockEnvironment_setInvocation_Call) Run(run func(inv rideType)) *MockEnvironment_setInvocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 rideType
		if args[0] != nil {
			arg0 = args[0].(rideType)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEnvironment_setInvocation_Call) Return() *MockEnvironment_setInvocation_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnvironment_setInvocation_Call) RunAndReturn(run func(inv rideType)) *MockEnvironment_setInvocation_Call {
	_c.Run(run)
	return _c
}

// setLibVersion provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) setLibVersion(v ast.LibraryVersion) {
	_mock.Called(v)
	return
}

// MockEnvironment_setLibVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setLibVersion'
type MockEnvironment_setLibVersion_Call struct {
	*mock.Call
}

// setLibVersion is a helper method to define mock.On call
//   - v ast.LibraryVersion
func (_e *MockEnvironment_Expecter) setLibVersion(v interface{}) *MockEnvironment_setLibVersion_Call {
	return &MockEnvironment_setLibVersion_Call{Call: _e.mock.On("setLibVersion", v)}
}

func (_c *MockEnvironment_setLibVersion_Call) Run(run func(v ast.LibraryVersion)) *MockEnvironment_setLibVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ast.LibraryVersion
		if args[0] != nil {
			arg0 = args[0].(ast.LibraryVersion)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEnvironment_setLibVersion_Call) Return() *MockEnvironment_setLibVersion_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnvironment_setLibVersion_Call) RunAndReturn(run func(v ast.LibraryVersion)) *MockEnvironment_setLibVersion_Call {
	_c.Run(run)
	return _c
}

// setNewDAppAddress provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) setNewDAppAddress(address proto.WavesAddress) {
	_mock.Called(address)
	return
}

// MockEnvironment_setNewDAppAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setNewDAppAddress'
type MockEnvironment_setNewDAppAddress_Call struct {
	*mock.Call
}

// setNewDAppAddress is a helper method to define mock.On call
//   - address proto.WavesAddress
func (_e *MockEnvironment_Expecter) setNewDAppAddress(address interface{}) *MockEnvironment_setNewDAppAddress_Call {
	return &MockEnvironment_setNewDAppAddress_Call{Call: _e.mock.On("setNewDAppAddress", address)}
}

func (_c *MockEnvironment_setNewDAppAddress_Call) Run(run func(address proto.WavesAddress)) *MockEnvironment_setNewDAppAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 proto.WavesAddress
		if args[0] != nil {
			arg0 = args[0].(proto.WavesAddress)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEnvironment_setNewDAppAddress_Call) Return() *MockEnvironment_setNewDAppAddress_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEnvironment_setNewDAppAddress_Call) RunAndReturn(run func(address proto.WavesAddress)) *MockEnvironment_setNewDAppAddress_Call {
	_c.Run(run)
	return _c
}

// state provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) state() types.SmartState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for state")
	}

	var r0 types.SmartState
	if returnFunc, ok := ret.Get(0).(func() types.SmartState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.SmartState)
		}
	}
	return r0
}

// MockEnvironment_state_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'state'
type MockEnvironment_state_Call struct {
	*mock.Call
}

// state is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) state() *MockEnvironment_state_Call {
	return &MockEnvironment_state_Call{Call: _e.mock.On("state")}
}

func (_c *MockEnvironment_state_Call) Run(run func()) *MockEnvironment_state_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_state_Call) Return(smartState types.SmartState) *MockEnvironment_state_Call {
	_c.Call.Return(smartState)
	return _c
}

func (_c *MockEnvironment_state_Call) RunAndReturn(run func() types.SmartState) *MockEnvironment_state_Call {
	_c.Call.Return(run)
	return _c
}

// takeString provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) takeString(s string, n int) rideString {
	ret := _mock.Called(s, n)

	if len(ret) == 0 {
		panic("no return value specified for takeString")
	}

	var r0 rideString
	if returnFunc, ok := ret.Get(0).(func(string, int) rideString); ok {
		r0 = returnFunc(s, n)
	} else {
		r0 = ret.Get(0).(rideString)
	}
	return r0
}

// MockEnvironment_takeString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'takeString'
type MockEnvironment_takeString_Call struct {
	*mock.Call
}

// takeString is a helper method to define mock.On call
//   - s string
//   - n int
func (_e *MockEnvironment_Expecter) takeString(s interface{}, n interface{}) *MockEnvironment_takeString_Call {
	return &MockEnvironment_takeString_Call{Call: _e.mock.On("takeString", s, n)}
}

func (_c *MockEnvironment_takeString_Call) Run(run func(s string, n int)) *MockEnvironment_takeString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnvironment_takeString_Call) Return(rideStringMoqParam rideString) *MockEnvironment_takeString_Call {
	_c.Call.Return(rideStringMoqParam)
	return _c
}

func (_c *MockEnvironment_takeString_Call) RunAndReturn(run func(s string, n int) rideString) *MockEnvironment_takeString_Call {
	_c.Call.Return(run)
	return _c
}

// this provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) this() rideType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for this")
	}

	var r0 rideType
	if returnFunc, ok := ret.Get(0).(func() rideType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rideType)
		}
	}
	return r0
}

// MockEnvironment_this_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'this'
type MockEnvironment_this_Call struct {
	*mock.Call
}

// this is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) this() *MockEnvironment_this_Call {
	return &MockEnvironment_this_Call{Call: _e.mock.On("this")}
}

func (_c *MockEnvironment_this_Call) Run(run func()) *MockEnvironment_this_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_this_Call) Return(rideTypeMoqParam rideType) *MockEnvironment_this_Call {
	_c.Call.Return(rideTypeMoqParam)
	return _c
}

func (_c *MockEnvironment_this_Call) RunAndReturn(run func() rideType) *MockEnvironment_this_Call {
	_c.Call.Return(run)
	return _c
}

// timestamp provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) timestamp() uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for timestamp")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// MockEnvironment_timestamp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'timestamp'
type MockEnvironment_timestamp_Call struct {
	*mock.Call
}

// timestamp is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) timestamp() *MockEnvironment_timestamp_Call {
	return &MockEnvironment_timestamp_Call{Call: _e.mock.On("timestamp")}
}

func (_c *MockEnvironment_timestamp_Call) Run(run func()) *MockEnvironment_timestamp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_timestamp_Call) Return(v uint64) *MockEnvironment_timestamp_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockEnvironment_timestamp_Call) RunAndReturn(run func() uint64) *MockEnvironment_timestamp_Call {
	_c.Call.Return(run)
	return _c
}

// transaction provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) transaction() rideType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for transaction")
	}

	var r0 rideType
	if returnFunc, ok := ret.Get(0).(func() rideType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rideType)
		}
	}
	return r0
}

// MockEnvironment_transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'transaction'
type MockEnvironment_transaction_Call struct {
	*mock.Call
}

// transaction is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) transaction() *MockEnvironment_transaction_Call {
	return &MockEnvironment_transaction_Call{Call: _e.mock.On("transaction")}
}

func (_c *MockEnvironment_transaction_Call) Run(run func()) *MockEnvironment_transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_transaction_Call) Return(rideTypeMoqParam rideType) *MockEnvironment_transaction_Call {
	_c.Call.Return(rideTypeMoqParam)
	return _c
}

func (_c *MockEnvironment_transaction_Call) RunAndReturn(run func() rideType) *MockEnvironment_transaction_Call {
	_c.Call.Return(run)
	return _c
}

// txID provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) txID() rideType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for txID")
	}

	var r0 rideType
	if returnFunc, ok := ret.Get(0).(func() rideType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rideType)
		}
	}
	return r0
}

// MockEnvironment_txID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'txID'
type MockEnvironment_txID_Call struct {
	*mock.Call
}

// txID is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) txID() *MockEnvironment_txID_Call {
	return &MockEnvironment_txID_Call{Call: _e.mock.On("txID")}
}

func (_c *MockEnvironment_txID_Call) Run(run func()) *MockEnvironment_txID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_txID_Call) Return(rideTypeMoqParam rideType) *MockEnvironment_txID_Call {
	_c.Call.Return(rideTypeMoqParam)
	return _c
}

func (_c *MockEnvironment_txID_Call) RunAndReturn(run func() rideType) *MockEnvironment_txID_Call {
	_c.Call.Return(run)
	return _c
}

// validateInternalPayments provides a mock function for the type MockEnvironment
func (_mock *MockEnvironment) validateInternalPayments() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for validateInternalPayments")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEnvironment_validateInternalPayments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'validateInternalPayments'
type MockEnvironment_validateInternalPayments_Call struct {
	*mock.Call
}

// validateInternalPayments is a helper method to define mock.On call
func (_e *MockEnvironment_Expecter) validateInternalPayments() *MockEnvironment_validateInternalPayments_Call {
	return &MockEnvironment_validateInternalPayments_Call{Call: _e.mock.On("validateInternalPayments")}
}

func (_c *MockEnvironment_validateInternalPayments_Call) Run(run func()) *MockEnvironment_validateInternalPayments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnvironment_validateInternalPayments_Call) Return(b bool) *MockEnvironment_validateInternalPayments_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEnvironment_validateInternalPayments_Call) RunAndReturn(run func() bool) *MockEnvironment_validateInternalPayments_Call {
	_c.Call.Return(run)
	return _c
}
