// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ride

import (
	"github.com/wavesplatform/gowaves/pkg/proto"
	"github.com/wavesplatform/gowaves/pkg/types"
	"sync"
)

// Ensure, that MockRideEnvironment does implement RideEnvironment.
// If this is not the case, regenerate this file with moq.
var _ RideEnvironment = &MockRideEnvironment{}

// MockRideEnvironment is a mock implementation of RideEnvironment.
//
//     func TestSomethingThatUsesRideEnvironment(t *testing.T) {
//
//         // make and configure a mocked RideEnvironment
//         mockedRideEnvironment := &MockRideEnvironment{
//             actionsFunc: func() []proto.ScriptAction {
// 	               panic("mock out the actions method")
//             },
//             appendActionFunc: func(action proto.ScriptAction)  {
// 	               panic("mock out the appendAction method")
//             },
//             appendActionsFunc: func(actions []proto.ScriptAction)  {
// 	               panic("mock out the appendActions method")
//             },
//             applyToStateFunc: func(actions []proto.ScriptAction) error {
// 	               panic("mock out the applyToState method")
//             },
//             blockFunc: func() rideObject {
// 	               panic("mock out the block method")
//             },
//             checkMessageLengthFunc: func(in1 int) bool {
// 	               panic("mock out the checkMessageLength method")
//             },
//             heightFunc: func() rideInt {
// 	               panic("mock out the height method")
//             },
//             invocationFunc: func() rideObject {
// 	               panic("mock out the invocation method")
//             },
//             invocationSysParamFunc: func() InvocationSysFuncParameters {
// 	               panic("mock out the invocationSysParam method")
//             },
//             schemeFunc: func() byte {
// 	               panic("mock out the scheme method")
//             },
//             setInvocationSysParamFunc: func(invokeSysPar InvocationSysFuncParameters)  {
// 	               panic("mock out the setInvocationSysParam method")
//             },
//             setNewDAppAddressFunc: func(address proto.Address)  {
// 	               panic("mock out the setNewDAppAddress method")
//             },
//             smartAppendActionsFunc: func(actions []proto.ScriptAction) error {
// 	               panic("mock out the smartAppendActions method")
//             },
//             stateFunc: func() types.SmartState {
// 	               panic("mock out the state method")
//             },
//             thisFunc: func() rideType {
// 	               panic("mock out the this method")
//             },
//             transactionFunc: func() rideObject {
// 	               panic("mock out the transaction method")
//             },
//             txIDFunc: func() rideType {
// 	               panic("mock out the txID method")
//             },
//         }
//
//         // use mockedRideEnvironment in code that requires RideEnvironment
//         // and then make assertions.
//
//     }
type MockRideEnvironment struct {
	// actionsFunc mocks the actions method.
	actionsFunc func() []proto.ScriptAction

	// appendActionFunc mocks the appendAction method.
	appendActionFunc func(action proto.ScriptAction)

	// appendActionsFunc mocks the appendActions method.
	appendActionsFunc func(actions []proto.ScriptAction)

	// applyToStateFunc mocks the applyToState method.
	applyToStateFunc func(actions []proto.ScriptAction) error

	// blockFunc mocks the block method.
	blockFunc func() rideObject

	// checkMessageLengthFunc mocks the checkMessageLength method.
	checkMessageLengthFunc func(in1 int) bool

	// heightFunc mocks the height method.
	heightFunc func() rideInt

	// invocationFunc mocks the invocation method.
	invocationFunc func() rideObject

	// invocationSysParamFunc mocks the invocationSysParam method.
	invocationSysParamFunc func() InvocationSysFuncParameters

	// schemeFunc mocks the scheme method.
	schemeFunc func() byte

	// setInvocationSysParamFunc mocks the setInvocationSysParam method.
	setInvocationSysParamFunc func(invokeSysPar InvocationSysFuncParameters)

	// setNewDAppAddressFunc mocks the setNewDAppAddress method.
	setNewDAppAddressFunc func(address proto.Address)

	// smartAppendActionsFunc mocks the smartAppendActions method.
	smartAppendActionsFunc func(actions []proto.ScriptAction) error

	// stateFunc mocks the state method.
	stateFunc func() types.SmartState

	// thisFunc mocks the this method.
	thisFunc func() rideType

	// transactionFunc mocks the transaction method.
	transactionFunc func() rideObject

	// txIDFunc mocks the txID method.
	txIDFunc func() rideType

	// calls tracks calls to the methods.
	calls struct {
		// actions holds details about calls to the actions method.
		actions []struct {
		}
		// appendAction holds details about calls to the appendAction method.
		appendAction []struct {
			// Action is the action argument value.
			Action proto.ScriptAction
		}
		// appendActions holds details about calls to the appendActions method.
		appendActions []struct {
			// Actions is the actions argument value.
			Actions []proto.ScriptAction
		}
		// applyToState holds details about calls to the applyToState method.
		applyToState []struct {
			// Actions is the actions argument value.
			Actions []proto.ScriptAction
		}
		// block holds details about calls to the block method.
		block []struct {
		}
		// checkMessageLength holds details about calls to the checkMessageLength method.
		checkMessageLength []struct {
			// In1 is the in1 argument value.
			In1 int
		}
		// height holds details about calls to the height method.
		height []struct {
		}
		// invocation holds details about calls to the invocation method.
		invocation []struct {
		}
		// invocationSysParam holds details about calls to the invocationSysParam method.
		invocationSysParam []struct {
		}
		// scheme holds details about calls to the scheme method.
		scheme []struct {
		}
		// setInvocationSysParam holds details about calls to the setInvocationSysParam method.
		setInvocationSysParam []struct {
			// InvokeSysPar is the invokeSysPar argument value.
			InvokeSysPar InvocationSysFuncParameters
		}
		// setNewDAppAddress holds details about calls to the setNewDAppAddress method.
		setNewDAppAddress []struct {
			// Address is the address argument value.
			Address proto.Address
		}
		// smartAppendActions holds details about calls to the smartAppendActions method.
		smartAppendActions []struct {
			// Actions is the actions argument value.
			Actions []proto.ScriptAction
		}
		// state holds details about calls to the state method.
		state []struct {
		}
		// this holds details about calls to the this method.
		this []struct {
		}
		// transaction holds details about calls to the transaction method.
		transaction []struct {
		}
		// txID holds details about calls to the txID method.
		txID []struct {
		}
	}
	lockactions               sync.RWMutex
	lockappendAction          sync.RWMutex
	lockappendActions         sync.RWMutex
	lockapplyToState          sync.RWMutex
	lockblock                 sync.RWMutex
	lockcheckMessageLength    sync.RWMutex
	lockheight                sync.RWMutex
	lockinvocation            sync.RWMutex
	lockinvocationSysParam    sync.RWMutex
	lockscheme                sync.RWMutex
	locksetInvocationSysParam sync.RWMutex
	locksetNewDAppAddress     sync.RWMutex
	locksmartAppendActions    sync.RWMutex
	lockstate                 sync.RWMutex
	lockthis                  sync.RWMutex
	locktransaction           sync.RWMutex
	locktxID                  sync.RWMutex
}

// actions calls actionsFunc.
func (mock *MockRideEnvironment) actions() []proto.ScriptAction {
	if mock.actionsFunc == nil {
		panic("MockRideEnvironment.actionsFunc: method is nil but RideEnvironment.actions was just called")
	}
	callInfo := struct {
	}{}
	mock.lockactions.Lock()
	mock.calls.actions = append(mock.calls.actions, callInfo)
	mock.lockactions.Unlock()
	return mock.actionsFunc()
}

// actionsCalls gets all the calls that were made to actions.
// Check the length with:
//     len(mockedRideEnvironment.actionsCalls())
func (mock *MockRideEnvironment) actionsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockactions.RLock()
	calls = mock.calls.actions
	mock.lockactions.RUnlock()
	return calls
}

// appendAction calls appendActionFunc.
func (mock *MockRideEnvironment) appendAction(action proto.ScriptAction) {
	if mock.appendActionFunc == nil {
		return
		//panic("MockRideEnvironment.appendActionFunc: method is nil but RideEnvironment.appendAction was just called")
	}
	callInfo := struct {
		Action proto.ScriptAction
	}{
		Action: action,
	}
	mock.lockappendAction.Lock()
	mock.calls.appendAction = append(mock.calls.appendAction, callInfo)
	mock.lockappendAction.Unlock()
	mock.appendActionFunc(action)
}

// appendActionCalls gets all the calls that were made to appendAction.
// Check the length with:
//     len(mockedRideEnvironment.appendActionCalls())
func (mock *MockRideEnvironment) appendActionCalls() []struct {
	Action proto.ScriptAction
} {
	var calls []struct {
		Action proto.ScriptAction
	}
	mock.lockappendAction.RLock()
	calls = mock.calls.appendAction
	mock.lockappendAction.RUnlock()
	return calls
}

// appendActions calls appendActionsFunc.
func (mock *MockRideEnvironment) appendActions(actions []proto.ScriptAction) {
	if mock.appendActionsFunc == nil {
		return
		//panic("MockRideEnvironment.appendActionsFunc: method is nil but RideEnvironment.appendActions was just called")
	}
	callInfo := struct {
		Actions []proto.ScriptAction
	}{
		Actions: actions,
	}
	mock.lockappendActions.Lock()
	mock.calls.appendActions = append(mock.calls.appendActions, callInfo)
	mock.lockappendActions.Unlock()
	mock.appendActionsFunc(actions)
}

// appendActionsCalls gets all the calls that were made to appendActions.
// Check the length with:
//     len(mockedRideEnvironment.appendActionsCalls())
func (mock *MockRideEnvironment) appendActionsCalls() []struct {
	Actions []proto.ScriptAction
} {
	var calls []struct {
		Actions []proto.ScriptAction
	}
	mock.lockappendActions.RLock()
	calls = mock.calls.appendActions
	mock.lockappendActions.RUnlock()
	return calls
}

// applyToState calls applyToStateFunc.
func (mock *MockRideEnvironment) applyToState(actions []proto.ScriptAction) error {
	if mock.applyToStateFunc == nil {
		return nil
		//panic("MockRideEnvironment.applyToStateFunc: method is nil but RideEnvironment.applyToState was just called")
	}
	callInfo := struct {
		Actions []proto.ScriptAction
	}{
		Actions: actions,
	}
	mock.lockapplyToState.Lock()
	mock.calls.applyToState = append(mock.calls.applyToState, callInfo)
	mock.lockapplyToState.Unlock()
	return mock.applyToStateFunc(actions)
}

// applyToStateCalls gets all the calls that were made to applyToState.
// Check the length with:
//     len(mockedRideEnvironment.applyToStateCalls())
func (mock *MockRideEnvironment) applyToStateCalls() []struct {
	Actions []proto.ScriptAction
} {
	var calls []struct {
		Actions []proto.ScriptAction
	}
	mock.lockapplyToState.RLock()
	calls = mock.calls.applyToState
	mock.lockapplyToState.RUnlock()
	return calls
}

// block calls blockFunc.
func (mock *MockRideEnvironment) block() rideObject {
	if mock.blockFunc == nil {
		panic("MockRideEnvironment.blockFunc: method is nil but RideEnvironment.block was just called")
	}
	callInfo := struct {
	}{}
	mock.lockblock.Lock()
	mock.calls.block = append(mock.calls.block, callInfo)
	mock.lockblock.Unlock()
	return mock.blockFunc()
}

// blockCalls gets all the calls that were made to block.
// Check the length with:
//     len(mockedRideEnvironment.blockCalls())
func (mock *MockRideEnvironment) blockCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockblock.RLock()
	calls = mock.calls.block
	mock.lockblock.RUnlock()
	return calls
}

// checkMessageLength calls checkMessageLengthFunc.
func (mock *MockRideEnvironment) checkMessageLength(in1 int) bool {
	if mock.checkMessageLengthFunc == nil {
		panic("MockRideEnvironment.checkMessageLengthFunc: method is nil but RideEnvironment.checkMessageLength was just called")
	}
	callInfo := struct {
		In1 int
	}{
		In1: in1,
	}
	mock.lockcheckMessageLength.Lock()
	mock.calls.checkMessageLength = append(mock.calls.checkMessageLength, callInfo)
	mock.lockcheckMessageLength.Unlock()
	return mock.checkMessageLengthFunc(in1)
}

// checkMessageLengthCalls gets all the calls that were made to checkMessageLength.
// Check the length with:
//     len(mockedRideEnvironment.checkMessageLengthCalls())
func (mock *MockRideEnvironment) checkMessageLengthCalls() []struct {
	In1 int
} {
	var calls []struct {
		In1 int
	}
	mock.lockcheckMessageLength.RLock()
	calls = mock.calls.checkMessageLength
	mock.lockcheckMessageLength.RUnlock()
	return calls
}

// height calls heightFunc.
func (mock *MockRideEnvironment) height() rideInt {
	if mock.heightFunc == nil {
		panic("MockRideEnvironment.heightFunc: method is nil but RideEnvironment.height was just called")
	}
	callInfo := struct {
	}{}
	mock.lockheight.Lock()
	mock.calls.height = append(mock.calls.height, callInfo)
	mock.lockheight.Unlock()
	return mock.heightFunc()
}

// heightCalls gets all the calls that were made to height.
// Check the length with:
//     len(mockedRideEnvironment.heightCalls())
func (mock *MockRideEnvironment) heightCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockheight.RLock()
	calls = mock.calls.height
	mock.lockheight.RUnlock()
	return calls
}

// invocation calls invocationFunc.
func (mock *MockRideEnvironment) invocation() rideObject {
	if mock.invocationFunc == nil {
		panic("MockRideEnvironment.invocationFunc: method is nil but RideEnvironment.invocation was just called")
	}
	callInfo := struct {
	}{}
	mock.lockinvocation.Lock()
	mock.calls.invocation = append(mock.calls.invocation, callInfo)
	mock.lockinvocation.Unlock()
	return mock.invocationFunc()
}

// invocationCalls gets all the calls that were made to invocation.
// Check the length with:
//     len(mockedRideEnvironment.invocationCalls())
func (mock *MockRideEnvironment) invocationCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockinvocation.RLock()
	calls = mock.calls.invocation
	mock.lockinvocation.RUnlock()
	return calls
}

// invocationSysParam calls invocationSysParamFunc.
func (mock *MockRideEnvironment) invocationSysParam() InvocationSysFuncParameters {
	if mock.invocationSysParamFunc == nil {
		return InvocationSysFuncParameters{}
		//panic("MockRideEnvironment.invocationSysParamFunc: method is nil but RideEnvironment.invocationSysParam was just called")
	}
	callInfo := struct {
	}{}
	mock.lockinvocationSysParam.Lock()
	mock.calls.invocationSysParam = append(mock.calls.invocationSysParam, callInfo)
	mock.lockinvocationSysParam.Unlock()
	return mock.invocationSysParamFunc()
}

// invocationSysParamCalls gets all the calls that were made to invocationSysParam.
// Check the length with:
//     len(mockedRideEnvironment.invocationSysParamCalls())
func (mock *MockRideEnvironment) invocationSysParamCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockinvocationSysParam.RLock()
	calls = mock.calls.invocationSysParam
	mock.lockinvocationSysParam.RUnlock()
	return calls
}

// scheme calls schemeFunc.
func (mock *MockRideEnvironment) scheme() byte {
	if mock.schemeFunc == nil {
		panic("MockRideEnvironment.schemeFunc: method is nil but RideEnvironment.scheme was just called")
	}
	callInfo := struct {
	}{}
	mock.lockscheme.Lock()
	mock.calls.scheme = append(mock.calls.scheme, callInfo)
	mock.lockscheme.Unlock()
	return mock.schemeFunc()
}

// schemeCalls gets all the calls that were made to scheme.
// Check the length with:
//     len(mockedRideEnvironment.schemeCalls())
func (mock *MockRideEnvironment) schemeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockscheme.RLock()
	calls = mock.calls.scheme
	mock.lockscheme.RUnlock()
	return calls
}

// setInvocationSysParam calls setInvocationSysParamFunc.
func (mock *MockRideEnvironment) setInvocationSysParam(invokeSysPar InvocationSysFuncParameters) {
	if mock.setInvocationSysParamFunc == nil {
		panic("MockRideEnvironment.setInvocationSysParamFunc: method is nil but RideEnvironment.setInvocationSysParam was just called")
	}
	callInfo := struct {
		InvokeSysPar InvocationSysFuncParameters
	}{
		InvokeSysPar: invokeSysPar,
	}
	mock.locksetInvocationSysParam.Lock()
	mock.calls.setInvocationSysParam = append(mock.calls.setInvocationSysParam, callInfo)
	mock.locksetInvocationSysParam.Unlock()
	mock.setInvocationSysParamFunc(invokeSysPar)
}

// setInvocationSysParamCalls gets all the calls that were made to setInvocationSysParam.
// Check the length with:
//     len(mockedRideEnvironment.setInvocationSysParamCalls())
func (mock *MockRideEnvironment) setInvocationSysParamCalls() []struct {
	InvokeSysPar InvocationSysFuncParameters
} {
	var calls []struct {
		InvokeSysPar InvocationSysFuncParameters
	}
	mock.locksetInvocationSysParam.RLock()
	calls = mock.calls.setInvocationSysParam
	mock.locksetInvocationSysParam.RUnlock()
	return calls
}

// setNewDAppAddress calls setNewDAppAddressFunc.
func (mock *MockRideEnvironment) setNewDAppAddress(address proto.Address) {
	if mock.setNewDAppAddressFunc == nil {
		panic("MockRideEnvironment.setNewDAppAddressFunc: method is nil but RideEnvironment.setNewDAppAddress was just called")
	}
	callInfo := struct {
		Address proto.Address
	}{
		Address: address,
	}
	mock.locksetNewDAppAddress.Lock()
	mock.calls.setNewDAppAddress = append(mock.calls.setNewDAppAddress, callInfo)
	mock.locksetNewDAppAddress.Unlock()
	mock.setNewDAppAddressFunc(address)
}

// setNewDAppAddressCalls gets all the calls that were made to setNewDAppAddress.
// Check the length with:
//     len(mockedRideEnvironment.setNewDAppAddressCalls())
func (mock *MockRideEnvironment) setNewDAppAddressCalls() []struct {
	Address proto.Address
} {
	var calls []struct {
		Address proto.Address
	}
	mock.locksetNewDAppAddress.RLock()
	calls = mock.calls.setNewDAppAddress
	mock.locksetNewDAppAddress.RUnlock()
	return calls
}

// smartAppendActions calls smartAppendActionsFunc.
func (mock *MockRideEnvironment) smartAppendActions(actions []proto.ScriptAction) error {
	if mock.smartAppendActionsFunc == nil {
		return nil
		//panic("MockRideEnvironment.smartAppendActionsFunc: method is nil but RideEnvironment.smartAppendActions was just called")
	}
	callInfo := struct {
		Actions []proto.ScriptAction
	}{
		Actions: actions,
	}
	mock.locksmartAppendActions.Lock()
	mock.calls.smartAppendActions = append(mock.calls.smartAppendActions, callInfo)
	mock.locksmartAppendActions.Unlock()
	return mock.smartAppendActionsFunc(actions)
}

// smartAppendActionsCalls gets all the calls that were made to smartAppendActions.
// Check the length with:
//     len(mockedRideEnvironment.smartAppendActionsCalls())
func (mock *MockRideEnvironment) smartAppendActionsCalls() []struct {
	Actions []proto.ScriptAction
} {
	var calls []struct {
		Actions []proto.ScriptAction
	}
	mock.locksmartAppendActions.RLock()
	calls = mock.calls.smartAppendActions
	mock.locksmartAppendActions.RUnlock()
	return calls
}

// state calls stateFunc.
func (mock *MockRideEnvironment) state() types.SmartState {
	if mock.stateFunc == nil {
		panic("MockRideEnvironment.stateFunc: method is nil but RideEnvironment.state was just called")
	}
	callInfo := struct {
	}{}
	mock.lockstate.Lock()
	mock.calls.state = append(mock.calls.state, callInfo)
	mock.lockstate.Unlock()
	return mock.stateFunc()
}

// stateCalls gets all the calls that were made to state.
// Check the length with:
//     len(mockedRideEnvironment.stateCalls())
func (mock *MockRideEnvironment) stateCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockstate.RLock()
	calls = mock.calls.state
	mock.lockstate.RUnlock()
	return calls
}

// this calls thisFunc.
func (mock *MockRideEnvironment) this() rideType {
	if mock.thisFunc == nil {
		panic("MockRideEnvironment.thisFunc: method is nil but RideEnvironment.this was just called")
	}
	callInfo := struct {
	}{}
	mock.lockthis.Lock()
	mock.calls.this = append(mock.calls.this, callInfo)
	mock.lockthis.Unlock()
	return mock.thisFunc()
}

// thisCalls gets all the calls that were made to this.
// Check the length with:
//     len(mockedRideEnvironment.thisCalls())
func (mock *MockRideEnvironment) thisCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockthis.RLock()
	calls = mock.calls.this
	mock.lockthis.RUnlock()
	return calls
}

// transaction calls transactionFunc.
func (mock *MockRideEnvironment) transaction() rideObject {
	if mock.transactionFunc == nil {
		panic("MockRideEnvironment.transactionFunc: method is nil but RideEnvironment.transaction was just called")
	}
	callInfo := struct {
	}{}
	mock.locktransaction.Lock()
	mock.calls.transaction = append(mock.calls.transaction, callInfo)
	mock.locktransaction.Unlock()
	return mock.transactionFunc()
}

// transactionCalls gets all the calls that were made to transaction.
// Check the length with:
//     len(mockedRideEnvironment.transactionCalls())
func (mock *MockRideEnvironment) transactionCalls() []struct {
} {
	var calls []struct {
	}
	mock.locktransaction.RLock()
	calls = mock.calls.transaction
	mock.locktransaction.RUnlock()
	return calls
}

// txID calls txIDFunc.
func (mock *MockRideEnvironment) txID() rideType {
	if mock.txIDFunc == nil {
		panic("MockRideEnvironment.txIDFunc: method is nil but RideEnvironment.txID was just called")
	}
	callInfo := struct {
	}{}
	mock.locktxID.Lock()
	mock.calls.txID = append(mock.calls.txID, callInfo)
	mock.locktxID.Unlock()
	return mock.txIDFunc()
}

// txIDCalls gets all the calls that were made to txID.
// Check the length with:
//     len(mockedRideEnvironment.txIDCalls())
func (mock *MockRideEnvironment) txIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.locktxID.RLock()
	calls = mock.calls.txID
	mock.locktxID.RUnlock()
	return calls
}
