name: "Deploy node"
on:
  workflow_dispatch:
    inputs:
      network:
        required: true
        type: string
        description: "Waves network name"
      arch:
        required: true
        type: string
        description: "Machine architecture (amd64, arm64)"
        default: "amd64"

jobs:
  deploy:
    name: deploy-node
    uses: "./.github/workflows/deploy_node_to.yml"
    with:
      network: ${{ github.event.inputs.network }}
      arch: ${{ github.event.inputs.arch }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEPLOYMENT_SERVER: ${{ secrets.DEPLOYMENT_SERVER }}
      DEPLOYMENT_USER: ${{ secrets.DEPLOYMENT_USER }}
