name: "Deploy nodes"

permissions: { }

on:
  workflow_dispatch:
    inputs:
      arch:
        required: true
        type: string
        description: "Machine architecture (amd64, arm64)"
        default: "amd64"

jobs:
  deploy:
    name: deploy-node
    strategy:
      matrix:
        network: [ stagenet, testnet, mainnet ]
        arch: [ "${{ inputs.arch }}" ]
    uses: "./.github/workflows/deploy_node.yml"
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEPLOYMENT_SERVER: ${{ secrets.DEPLOYMENT_SERVER }}
      DEPLOYMENT_PORT: ${{ secrets.DEPLOYMENT_PORT }}
      DEPLOYMENT_USER: ${{ secrets.DEPLOYMENT_USER }}
    with:
      network: ${{ matrix.network }}
      arch: ${{ matrix.arch }}
