name: "ITestsWithRaceDetector"
on:
  workflow_dispatch:

permissions: { }

jobs:
  itest-race:
    name: integration_tests_with_race_detector
    if: (github.repository == 'wavesplatform/gowaves')
    uses: "./.github/workflows/run_itests.yml"
    with:
      itest-type: 'itest-race'
