name: "ITests"
on:
  workflow_dispatch:
  pull_request_review:
    types: [ submitted ]
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' && github.event_name != 'workflow_dispatch' }}

jobs:
  itest:
    name: integration_tests
    runs-on: self-hosted
    environment:
      name: ITests
    if: (github.event_name == 'workflow_dispatch' || github.event.review.state == 'APPROVED') && github.repository == 'wavesplatform/gowaves'

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.22.x
          check-latest: true
          cache: true
        id: go

      - name: Get dependencies
        run: go mod vendor

      - name: Tests
        run: make itest

      - name: Upload itest logs and configs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: itest_logs_and_configs
          path: |
            build/logs/
            build/config/
          if-no-files-found: warn
          retention-days: 5
