name: "ITestsWithRaceDetector"
on:
  workflow_dispatch:
  schedule:
    - cron: '21 21,00,03 * * *' # UTC time

permissions: { }

jobs:
  itest-race:
    name: integration_tests_with_race_detector
    if: (github.repository == 'wavesplatform/gowaves')
    uses: "./.github/workflows/run_itests.yml"
    with:
      itest-type: 'itest-race'
