name: "SmokeITests"
on:
  workflow_dispatch:
  schedule:
    - cron: '0,15,30,45 * * * *' # every 15 minutes

jobs:
  smoke_itest:
    name: smoke_integration_tests
    runs-on: self-hosted
    if: github.repository == 'wavesplatform/gowaves'

    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.20.x
          check-latest: true
          cache: true
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod vendor

      - name: Tests
        env:
          ITESTS_KEEP_DANGLING: false
        run: make smoke

      - name: Upload itest logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: smoke_itest_logs_by_schedule_${{ github.run_id }}
          path: build/logs/
          if-no-files-found: warn
          retention-days: 5
