name: "ITests"
on:
  workflow_dispatch:
  pull_request_review:
    types: [ submitted ]
    branches: [ master ]

jobs:
  itest:
    name: integration_tests
    runs-on: self-hosted
    environment:
      name: ITests
    if: (github.event_name == 'workflow_dispatch' || github.event.review.state == 'APPROVED') && github.repository == 'wavesplatform/gowaves'

    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.21.x
          check-latest: true
          cache: true
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod vendor

      - name: Tests
        run: make itest

      - name: Upload itest logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: itest_logs
          path: build/logs/
          if-no-files-found: warn
          retention-days: 5
