name: "ITestsWithRaceDetector"
on:
  workflow_dispatch:
  schedule:
    - cron: '21 22,23,00,01,02,03 * * *' # UTC time

jobs:
  itest-race:
    name: integration_tests_with_race_detector
    runs-on: self-hosted
    if: github.repository == 'wavesplatform/gowaves'

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v5.3.0
        with:
          go-version: 1.23.x
          check-latest: true
          cache: true
        id: go

      - name: Get dependencies
        run: go mod vendor

      - name: Tests
        run: make itest-race

      - name: Upload itest logs and configs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: itest_logs_and_configs
          path: |
            build/logs/
            build/config/
          if-no-files-found: warn
          retention-days: 5
