name: Publish Docker Image to GitHub Container Registry
run-name: Publish branch ${{ github.ref_name }} to tag ${{ inputs.dockerTag }}

on:
  workflow_dispatch:
    inputs:
      dockerTag:
        description: 'Docker Tag'
        required: true
        type: string
        default: 'latest'

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ inputs.dockerTag }}

permissions: { }

jobs:
  build:
    name: Build and Push Docker Image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go 1.25
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: 1.25.x
          check-latest: true
          cache: false

      - name: Get dependencies
        run: go mod vendor

      - name: Build node
        run: export PATH="$HOME/bin:$PATH"; make release-node

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: latest=false
          tags: |
            type=sha
            type=raw,value=${{ env.IMAGE_TAG }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.description="Waves Node"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v5
        id: push
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          build-args: ''
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
