name: "SmokeITests"
on:
  push

jobs:
  smoke:
    name: smoke_integration_tests
    runs-on: self-hosted
    environment:
      name: SmokeITests
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'wavesplatform/gowaves'

    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.20.x
          check-latest: true
          cache: true
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod vendor

      - name: Tests
        run: make smoke

      - name: Upload smoke itests logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: smoke_itests_logs
          path: build/logs/
          if-no-files-found: warn
          retention-days: 5
